#ifndef TASK_PRIORITIES_H
#define TASK_PRIORITIES_H

// Free RTOS task priorities
#define INDICATOR_TASK_PRIORITY (tskIDLE_PRIORITY  + 30)
#define MIDI_CLOCK_TASK_PRIORITY (tskIDLE_PRIORITY  + 15)
#define DEVICE_API_TASK_PRIORITY (tskIDLE_PRIORITY  + 20)
#endif // TASK_PRIORITIES_H